# Project 6 -- Tanay Patel

**TA Help:** (for instance) John Smith, Alice Jones, etc., list names of any TAs who helped you

- For example: Help with figuring out how to write a function (describe the tasks that they helped you with)

**Collaboration:** My Friend in CS, My Uncle, Another Student, etc., list names of any other people who helped you

(describe the tasks that they helped you with)
- For example: helped figuring out how to load the dataset.
- Another example: helped debug error with my plot.

**Internet Resources:** Stack Exchange, Stack Overflow, etc.

(describe any information that you learned from internet resources, including the URLs)
- data frames in Pandas versus R from StackOverflow  https://stackoverflow.com/questions/8991709/why-were-pandas-merges-in-python-faster-than-data-table-merges-in-r-in-2012

**ChatGPT, Gemini, Claude, etc:** Any language models or generative AI chatbots that helped you.

(if you used any such tools, please tell us here)
- For example:  I asked ChatGPT how to define a new data frames
- Another example:  Gemini told me how to make a function for sorting my data

- ***Link to AI Chat History***: Please share a link to your chat if you used AI (ex. ChatGPT Shared Links)
**OVERALL MESSAGE:** Any time that you used anything except your brain to solve the questions in these projects, you need to disclose such resources at the start of the project, with details about your usage of the tools.

**YOUR OWN WORK:** Even when you utilize other resources, do NOT just copy and paste.  Write all explanations in your own words, using several sentences in English, which are understandable and which you wrote (and did not just copy and paste).

## Question 1

In [1]:
import pandas as pd
myDF = pd.read_csv("/anvil/projects/tdm/data/flights/subset/2006.csv")

In [2]:
pd.set_option("display.max_columns", None)
myDF.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2006,1,11,3,743.0,745,1024.0,1018,US,343,N657AW,281.0,273.0,223.0,6.0,-2.0,ATL,PHX,1587,45,13,0,NaN,0,0,0,0,0,0
1,2006,1,11,3,1053.0,1053,1313.0,1318,US,613,N834AW,260.0,265.0,214.0,-5.0,0.0,ATL,PHX,1587,27,19,0,NaN,0,0,0,0,0,0
2,2006,1,11,3,1915.0,1915,2110.0,2133,US,617,N605AW,235.0,258.0,220.0,-23.0,0.0,ATL,PHX,1587,4,11,0,NaN,0,0,0,0,0,0
3,2006,1,11,3,1753.0,1755,1925.0,1933,US,300,N312AW,152.0,158.0,126.0,-8.0,-2.0,AUS,PHX,872,16,10,0,NaN,0,0,0,0,0,0
4,2006,1,11,3,824.0,832,1015.0,1015,US,765,N309AW,171.0,163.0,132.0,0.0,-8.0,AUS,PHX,872,27,12,0,NaN,0,0,0,0,0,0

In [3]:
pa_flights = myDF[myDF["Dest"] == "PHL"]

In [4]:
pa_flights["Origin"].nunique()

66

In [5]:
phl_avg_airtime_by_origin = (
    pa_flights.groupby("Origin")["AirTime"]
    .mean()
    .sort_values(ascending=False)
)

phl_avg_airtime_by_origin.head()

Origin
SFO    290.109422
OAK    289.584488
LAX    279.706140
SAN    278.428962
SEA    278.121287
Name: AirTime, dtype: float64

In [6]:
phl_avg_airtime_by_origin.loc["SFO"]

np.float64(290.1094224924012)

In [7]:
az_flights = myDF[myDF["Dest"] == "PHX"]

In [8]:
phx_avg_airtime_by_origin = (
    az_flights.groupby("Origin")["AirTime"]
    .mean()
    .sort_values(ascending=False)
)

phx_avg_airtime_by_origin.head()

Origin
HNL    378.044693
LIH    333.385593
KOA    319.184100
OGG    317.876420
PVD    314.596974
Name: AirTime, dtype: float64

In [9]:
phx_avg_airtime_by_origin["HNL"]

np.float64(378.0446927374302)

In question 1, we read in the 2006 flights subset dataset using the pandas library and saved it as myDF. Then we created a subset called pa_flights that only included flights whose destination was PHL. After that, we used .nunique() to find how many unique Origin airports had flights going to PHL and used .groupby() to calculate the average AirTime for each origin airport, and we repeated a similar process for flights whose destination was PHX.

## Question 2

In [10]:
top_20 = myDF["Dest"].value_counts().head(20).index.tolist()
top_20

['ATL',
 'ORD',
 'DFW',
 'LAX',
 'DEN',
 'IAH',
 'PHX',
 'LAS',
 'EWR',
 'SLC',
 'SFO',
 'BOS',
 'DTW',
 'LGA',
 'CVG',
 'MSP',
 'MCO',
 'CLT',
 'JFK',
 'PHL']

In [11]:
top_dests_df = myDF[myDF["Dest"].isin(top_20)]

In [12]:
result = top_dests_df.groupby(["Origin", "Dest"])["AirTime"].mean()

In [13]:
result.head()

Origin  Dest
ABE     ATL     99.765806
        CLT     76.243094
        CVG     86.536354
        DTW     75.500000
        JFK     38.750000
Name: AirTime, dtype: float64

In [14]:
result.unstack().head()

Dest,ATL,BOS,CLT,CVG,DEN,DFW,DTW,EWR,IAH,JFK,LAS,LAX,LGA,MCO,MSP,ORD,PHL,PHX,SFO,SLC
Origin,,,,,,,,,,,,,,,,,,,,
ABE,99.765806,NaN,76.243094,86.536354,NaN,NaN,75.5,NaN,NaN,38.75,NaN,NaN,38.5,NaN,NaN,105.341948,NaN,NaN,NaN,NaN
ABI,NaN,NaN,NaN,NaN,NaN,37.107903,NaN,NaN,NaN,NaN,NaN,144.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABQ,155.828894,NaN,NaN,150.654237,55.016649,76.081734,NaN,219.243243,103.270481,NaN,74.644799,99.820225,NaN,184.00831,126.507042,140.790524,NaN,56.551712,130.204451,77.405405
ABY,33.829287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.009756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In question 2, we found the 20 most popular destination airports using the .value_counts() function and saved the airport names as a list called top_20. Then we filtered the original dataframe so that it only contained flights whose destination was in the top_20 list. After that, we used .groupby() on both the Origin and Dest columns to calculate the average AirTime for each origin–destination pair and viewed the results.

## Question 3

In [15]:
ice_cream = pd.read_csv("/anvil/projects/tdm/data/icecream/combined/products.csv")

In [16]:
ice_cream["rating"].describe()

count    241.000000
mean       4.223237
std        0.620383
min        1.200000
25%        4.000000
50%        4.400000
75%        4.700000
max        5.000000
Name: rating, dtype: float64

In [34]:
pd.qcut(ice_cream["rating"], q=4)

0      (1.199, 4.0]
1      (1.199, 4.0]
2        (4.4, 4.7]
3      (1.199, 4.0]
4        (4.4, 4.7]
           ...
236    (1.199, 4.0]
237      (4.4, 4.7]
238    (1.199, 4.0]
239    (1.199, 4.0]
240    (1.199, 4.0]
Name: rating, Length: 241, dtype: category
Categories (4, interval[float64, right]): [(1.199, 4.0] < (4.0, 4.4] < (4.4, 4.7] < (4.7, 5.0]]

### Here is the range: [(1.199, 4.0] < (4.0, 4.4] < (4.4, 4.7] < (4.7, 5.0]]

In [18]:
ice_cream["rating_phrases"] = pd.qcut(
    ice_cream["rating"],
    q=4,
    labels=[
        "Wouldn't Recommend",
        "Needs Improvement",
        "Solid Choice",
        "Fan Favorite"
    ]
)

In [19]:
ice_cream.head()

,brand,key,name,subhead,description,rating,rating_count,ingredients,rating_phrases
0,bj,0_bj,Salted Caramel Core,Sweet Cream Ice Cream with Blonde Brownies & a...,Find your way to the ultimate ice cream experi...,3.7,208,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",Wouldn't Recommend
1,bj,1_bj,Netflix & Chilll'd™,Peanut Butter Ice Cream with Sweet & Salty Pre...,There’s something for everyone to watch on Net...,4.0,127,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",Wouldn't Recommend
2,bj,2_bj,Chip Happens,A Cold Mess of Chocolate Ice Cream with Fudge ...,Sometimes “chip” happens and everything’s a me...,4.7,130,"CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK,...",Solid Choice
3,bj,3_bj,Cannoli,Mascarpone Ice Cream with Fudge-Covered Pastry...,As a Limited Batch that captured the rapture o...,3.6,70,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",Wouldn't Recommend
4,bj,4_bj,Gimme S’more!™,Toasted Marshmallow Ice Cream with Chocolate C...,It’s a gimme: there’s always room for s’more. ...,4.5,281,"CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, ...",Solid Choice

In question 3, we read in the ice cream products dataset and examined the statistics of the rating column using .describe(). Then we used the .qcut() function to divide the rating values into four equal groups and looked at the ranges that were created. After that, we applied labels to each of these rating ranges and saved them in a new column called rating_phrases.

## Question 4

In [20]:
my_flights = pd.read_csv("/anvil/projects/tdm/data/flights/subset/1997.csv")

In [21]:
bins = [0, 300, 600, 900, 1200, 1500, 1800, 2100, 2400]
labels = [
    "Late Night", "Early Morning", "Morning", "Late Morning",
    "Afternoon", "Early Evening", "Evening", "Night"
]

In [22]:
my_flights["depart_times"] = pd.cut(my_flights["DepTime"], bins=bins, labels=labels)

In [23]:
my_flights["depart_times"].value_counts(sort=False)

depart_times
Late Night         40119
Early Morning      45068
Morning          1046463
Late Morning      968561
Afternoon         998262
Early Evening     997450
Evening           893498
Night             324659
Name: count, dtype: int64

In [24]:
my_flights["arrival_times"] = pd.cut(my_flights["ArrTime"], bins=bins, labels=labels)

In [25]:
my_flights["arrival_times"].value_counts(sort=False)

arrival_times
Late Night         88778
Early Morning      38472
Morning           479845
Late Morning      955399
Afternoon         951465
Early Evening    1015952
Evening          1011908
Night             760180
Name: count, dtype: int64

In [26]:
# BUSIEST DEPARTURE
my_flights["depart_times"].value_counts().idxmax()

'Morning'

In [27]:
# BUSIEST ARRIVAL
my_flights["arrival_times"].value_counts().idxmax()

'Early Evening'

In question 4, we read in the 1997 flights dataset and used the .cut() function to divide the DepTime column into several time ranges based on different periods of the day. We assigned labels such as Late Night, Early Morning, and Afternoon to these bins and saved the results as the new column depart_times. Then we repeated the same process for the ArrTime column to create the arrival_times column and examined which time ranges had the most flights.

## Question 5

In [28]:
march = my_flights[my_flights["Month"] == 3]

In [29]:
march_day_counts = march["DayOfWeek"].value_counts().sort_index()
all_months_day_counts = my_flights["DayOfWeek"].value_counts().sort_index()

In [30]:
print(march_day_counts)

DayOfWeek
1    76352
2    61070
3    61093
4    61100
5    61052
6    68031
7    72288
Name: count, dtype: int64

In [31]:
print(all_months_day_counts)

DayOfWeek
1    790298
2    791617
3    802130
4    785731
5    786342
6    706198
7    749527
Name: count, dtype: int64

In [32]:
total_airtime_table = my_flights.groupby(["DayOfWeek", "Month"])["AirTime"].sum().unstack()
total_airtime_table

Month,1,2,3,4,5,6,7,8,9,10,11,12
DayOfWeek,,,,,,,,,,,,
1,5820142.0,5996050.0,7450628.0,6032763.0,5943737.0,7525264.0,6100879.0,6104229.0,7425773.0,5954814.0,5990224.0,7521815.0
2,5894308.0,6014615.0,6036897.0,7438885.0,5973378.0,6023384.0,7587559.0,6088182.0,7471445.0,5977490.0,6012467.0,7485652.0
3,7265554.0,6062085.0,6047810.0,7510912.0,5976554.0,5988220.0,7577076.0,6109375.0,5945379.0,7473880.0,6059871.0,7239442.0
4,7310610.0,6065632.0,5998931.0,6021716.0,7487291.0,6029059.0,7567389.0,6120396.0,5943426.0,7506399.0,5682853.0,5824651.0
5,7415133.0,5992478.0,6028038.0,6061881.0,7528029.0,6046017.0,5840017.0,7627953.0,5915696.0,7477447.0,5761139.0,5989230.0
6,5463380.0,5457435.0,6930980.0,5540389.0,6793947.0,5688313.0,5628626.0,7087879.0,5374278.0,5319835.0,6785410.0,5518159.0
7,5643971.0,5719389.0,7284005.0,5808701.0,5645453.0,7321258.0,5920780.0,7247138.0,5694575.0,5697566.0,7231943.0,5819670.0

In [33]:
avg_airtime_table = my_flights.groupby(["DayOfWeek", "Month"])["AirTime"].mean().unstack()
avg_airtime_table

Month,1,2,3,4,5,6,7,8,9,10,11,12
DayOfWeek,,,,,,,,,,,,
1,100.970508,100.466640,100.662397,100.541023,100.238414,100.344881,101.004586,100.411715,99.970019,99.899577,100.911777,102.134739
2,101.115194,100.929907,101.207011,100.080520,99.805815,100.354609,100.721592,100.914669,100.216557,100.175800,101.082144,102.274183
3,102.297167,102.192937,100.902781,100.562492,99.758872,100.454950,100.926753,100.968054,99.828380,100.320537,102.033490,102.805237
4,102.142009,102.097829,100.558720,100.445638,100.072054,100.280413,100.256876,100.632960,99.800615,100.566699,102.355019,102.499754
5,101.678843,101.717414,100.624946,101.235508,99.996400,100.360490,100.459584,100.096488,99.062177,100.079596,103.148246,102.175649
6,103.763960,103.241236,103.319470,103.591590,102.258417,103.110791,102.922506,102.821235,101.735471,102.828549,104.742212,104.909960
7,101.902484,101.355491,101.988309,101.823076,101.125873,101.171257,101.253185,102.014893,100.157855,101.322485,102.244288,103.504962

In question 5, we selected flights from a specific month and compared the value counts of the DayOfWeek column for that month with the value counts across all months. Then we used the .groupby() method to calculate the total AirTime across the days of the week and months and displayed the results in a table format using .unstack(). Finally, we created another similar table that calculated the average AirTime instead of the total.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/